# Generated by Django 4.2.27 on 2026-03-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField(help_text='Confidence score as a percentage (0–100)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detections/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Detection Event',
                'verbose_name_plural': 'Detection Events',
                'ordering': ['-detected_at'],
            },
        ),
    ]
