# Generated by Django 4.2.27 on 2026-03-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionEvent',
        ),
    ]
