# Generated by Django 4.2.27 on 2026-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0004_forestofficer_alter_userdb_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeProtectionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('leader_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('number_of_members', models.IntegerField()),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='wildlife_teams/')),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='forestofficer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
