# Generated by Django 4.2.27 on 2026-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0005_wildlifeprotectionteam_alter_forestofficer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=255)),
                ('reporter_email', models.CharField(blank=True, max_length=255)),
                ('reporter_phone', models.CharField(blank=True, max_length=30)),
                ('animal_name', models.CharField(help_text='Name of the animal (e.g. Elephant, Tiger)', max_length=255)),
                ('description', models.TextField(help_text='Describe the emergency situation in detail')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_address', models.TextField(blank=True, help_text='Human-readable address if available')),
                ('location_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SOS Report',
                'verbose_name_plural': 'SOS Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
