# Generated by Django 4.2.27 on 2026-03-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0008_remove_wildlifeprotectionteam_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='location',
        ),
        migrations.AddField(
            model_name='userdb',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='location_address',
            field=models.TextField(blank=True, help_text='Human-readable address if available'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
