# Generated by Django 4.2.27 on 2026-03-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0009_remove_userdb_location_userdb_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_image', models.ImageField(blank=True, help_text='Snapshot captured at detection time', null=True, upload_to='detections/%Y/%m/%d/')),
                ('confidence', models.FloatField(help_text='Detection confidence (0–100)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_address', models.TextField(blank=True)),
                ('location_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in metres', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('notified_officers', models.ManyToManyField(blank=True, related_name='detection_notifications', to='detection_app.forestofficer')),
                ('notified_teams', models.ManyToManyField(blank=True, related_name='detection_notifications', to='detection_app.wildlifeprotectionteam')),
                ('notified_users', models.ManyToManyField(blank=True, related_name='detection_notifications', to='detection_app.userdb')),
            ],
            options={
                'verbose_name': 'Wildlife Detection',
                'verbose_name_plural': 'Wildlife Detections',
                'ordering': ['-detected_at'],
            },
        ),
    ]
