# Generated by Django 4.2.27 on 2026-03-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0010_wildlifedetection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WildlifeDetection',
        ),
    ]
