# Generated by Django 4.2.27 on 2026-03-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0011_delete_wildlifedetection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('confidence', models.FloatField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_address', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
